'use client'

/**
 * "Why" — the diagnostic engine's output.
 *
 * Findings arrive pre-ranked by severity from the engine. Nothing here is
 * generated by an LLM: every card is a rule that fired on the user's own
 * numbers, with the numbers shown, so a claim can always be traced back.
 */

import { Card } from '@/components/ui/card'
import type { AnalyticsPayload, Severity } from '@/lib/analytics/types'
import { DataTable, EmptyPanel, FindingCard, SectionHeading, fmtKcal } from './chart-kit'
import { CheckCircle2 } from 'lucide-react'

const GROUPS: { severity: Severity; heading: string; blurb: string }[] = [
  { severity: 'critical', heading: 'Fix these first', blurb: 'These are actively working against your goal.' },
  { severity: 'serious', heading: 'Costing you real progress', blurb: 'Worth changing this week.' },
  { severity: 'warning', heading: 'Worth watching', blurb: 'Not urgent, but they add up.' },
  { severity: 'insight', heading: 'Things you should know', blurb: 'Context that changes how you read the rest.' },
  { severity: 'good', heading: 'What is already working', blurb: 'Protect these — they are the reason anything is working.' },
]

export function DiagnosticsView({ data }: { data: AnalyticsPayload }) {
  const { findings, training } = data

  if (findings.length === 0) {
    return (
      <EmptyPanel
        title="Not enough data to diagnose anything yet"
        body="The diagnostic rules stay silent rather than guess. Log food, workouts and a morning weight for a couple of weeks and this page fills in with specific, numbered explanations."
      />
    )
  }

  const counts = GROUPS.map((g) => ({ ...g, items: findings.filter((f) => f.severity === g.severity) }))

  // Rest days where nothing was eaten on paper — the days the user asked about.
  const unloggedNoTraining = training.missedDays.filter((d) => !d.logged).slice(0, 40)
  const restWithSurplus = training.missedDays
    .filter((d) => (d.balance ?? 0) > 0)
    .sort((a, b) => (b.balance ?? 0) - (a.balance ?? 0))
    .slice(0, 20)

  return (
    <div className="space-y-6">
      <Card className="p-4">
        <p className="text-sm text-muted-foreground leading-relaxed">
          Each card below is a rule that fired on your own numbers — the evidence row shows the exact values it
          used. Rules that could not clear their own data bar stayed quiet, so an empty section means
          &ldquo;nothing to say&rdquo;, not &ldquo;all clear&rdquo;.
        </p>
        <div className="mt-3 flex flex-wrap gap-x-5 gap-y-1.5 text-xs">
          {counts
            .filter((c) => c.items.length > 0)
            .map((c) => (
              <span key={c.severity} className="text-muted-foreground">
                <span className="font-semibold text-foreground tabular-nums">{c.items.length}</span> {c.heading.toLowerCase()}
              </span>
            ))}
        </div>
      </Card>

      {counts.map(
        (g) =>
          g.items.length > 0 && (
            <div key={g.severity} className="space-y-3">
              <SectionHeading title={g.heading} hint={g.blurb} />
              {g.items.map((f) => (
                <FindingCard key={f.id} finding={f} />
              ))}
            </div>
          )
      )}

      {/* ---- The specific question: which days did I skip, and what did I eat? ---- */}
      {restWithSurplus.length > 0 && (
        <div className="space-y-3">
          <SectionHeading
            title="Rest days that ended over maintenance"
            hint="No training, still a surplus. These are the days doing the damage — worst first."
          />
          <Card className="p-4">
            <DataTable
              rows={restWithSurplus}
              columns={[
                { key: 'date', header: 'Date', render: (r) => `${r.label} (${r.weekday})` },
                { key: 'intake', header: 'Eaten', align: 'right', render: (r) => fmtKcal(r.intake) },
                {
                  key: 'balance',
                  header: 'Over maintenance',
                  align: 'right',
                  render: (r) => (
                    <span className="font-semibold text-red-600 dark:text-red-400">
                      +{Math.round(r.balance ?? 0).toLocaleString()}
                    </span>
                  ),
                },
              ]}
            />
          </Card>
        </div>
      )}

      {unloggedNoTraining.length > 0 && (
        <div className="space-y-3">
          <SectionHeading
            title="Days with no workout and no food logged"
            hint="The blind spot. These days are invisible to every average on this page."
          />
          <Card className="p-4">
            <p className="mb-3 text-sm text-muted-foreground leading-relaxed">
              You did not train on these {unloggedNoTraining.length} days and did not record what you ate. Missing
              days are not neutral — they skew every average upward in your favour. Even a one-line estimate
              (&ldquo;roughly 2 500 kcal, no workout&rdquo;) makes them count.
            </p>
            <div className="flex flex-wrap gap-1.5">
              {unloggedNoTraining.map((d) => (
                <span
                  key={d.date}
                  className="rounded-md border border-border px-2 py-1 text-[11px] tabular-nums text-muted-foreground"
                >
                  {d.label} · {d.weekday}
                </span>
              ))}
            </div>
          </Card>
        </div>
      )}

      {counts.find((c) => c.severity === 'good')?.items.length === 0 && (
        <Card className="flex items-center gap-3 p-4">
          <CheckCircle2 className="h-5 w-5 flex-shrink-0 text-muted-foreground" />
          <p className="text-sm text-muted-foreground">
            No &ldquo;already working&rdquo; findings in this range yet — those need a few consistent weeks to earn.
          </p>
        </Card>
      )}
    </div>
  )
}
