import { Navigation } from '@/components/navigation'
import { IngestorForm } from '@/components/ingestor-form'

export default function IngestorPage() {
  return (
    <div className="flex flex-col md:flex-row min-h-screen">
      <Navigation />
      <main className="flex-1 p-4 md:p-8 pb-24 md:pb-8">
        <div className="max-w-3xl mx-auto space-y-6">
          <header>
            <h1 className="text-3xl font-bold tracking-tight text-foreground">Paste Ingestor</h1>
            <p className="text-muted-foreground mt-1">
              Paste JSON data generated by ChatGPT to store in your personal database
            </p>
          </header>
          
          <IngestorForm />
        </div>
      </main>
    </div>
  )
}
